### GET ALL EMPLOYEES
GET http://localhost:4004/odata/v4/leave-management/Employees
Content-Type: application/json

### CREATE USER EMPLOYEE
POST http://localhost:4004/odata/v4/leave-management/Employees
Content-Type: application/json

{
  "EmployeeID": "EMP1008",
  "Name": "Vishal",
  "Email": "vishal@test.com",
  "Department": "IT",
  "Role": "Employee"
}

### CREATE DUPLICATE EMPLOYEE
POST http://localhost:4004/odata/v4/leave-management/Employees
Content-Type: application/json

{
  "EmployeeID": "EMP1008",
  "Name": "Vishal",
  "Email": "vishal@test.com",
  "Department": "IT",
  "Role": "Employee"
}

### CREATE ADMIN EMPLOYEE
POST http://localhost:4004/odata/v4/leave-management/Employees
Content-Type: application/json

{
  "EmployeeID": "EMP1007",
  "Name": "Saumya",
  "Email": "saumya@test.com",
  "Department": "HR",
  "Role": "Admin"
}

### GET PENDING LEAVES
GET http://localhost:4004/odata/v4/leave-management/getPendingLeaves()
Content-Type: application/json

### CREATE LEAVE REQUEST
POST http://localhost:4004/odata/v4/leave-management/LeaveRequests
Content-Type: application/json

{
  "LeaveID": "LV1008",
  "StartDate": "2026-06-20",
  "EndDate": "2026-06-22",
  "Reason": "Medical Leave",
  "AppliedOn": "2026-06-15",
  "employee_ID": "13829769-36c4-4e19-be07-07c72a37c609"
}

### CREATE LEAVE REQUEST WITH SAME LEAVEID
POST http://localhost:4004/odata/v4/leave-management/LeaveRequests
Content-Type: application/json

{
  "LeaveID": "LV1008",
  "StartDate": "2026-06-20",
  "EndDate": "2026-06-22",
  "Reason": "Medical Leave",
  "AppliedOn": "2026-06-15",
  "employee_ID": "13829769-36c4-4e19-be07-07c72a37c609"
}

### CREATE LEAVE REQUEST WITHOUT REASON
POST http://localhost:4004/odata/v4/leave-management/LeaveRequests
Content-Type: application/json

{
  "LeaveID": "LV1009",
  "StartDate": "2026-06-20",
  "EndDate": "2026-06-22",
  "Reason": "",
  "AppliedOn": "2026-06-15",
  "employee_ID": "13829769-36c4-4e19-be07-07c72a37c609"
}

### CREATE LEAVE REQUEST WITH WRONG DATES
POST http://localhost:4004/odata/v4/leave-management/LeaveRequests
Content-Type: application/json

{
  "LeaveID": "LV1009",
  "StartDate": "2026-06-25",
  "EndDate": "2026-06-20",
  "Reason": "Invalid Dates Test",
  "AppliedOn": "2026-06-15",
  "employee_ID": "13829769-36c4-4e19-be07-07c72a37c609"
}

### UPDATE LEAVE REQUEST
PATCH http://localhost:4004/odata/v4/leave-management/LeaveRequests(2368209b-b2e1-466c-8c81-06779ef1409c)
Content-Type: application/json

{
  "Reason": "Updated medical leave reason"
}

### APPROVE LEAVE REQUEST
POST http://localhost:4004/odata/v4/leave-management/approveLeave
Content-Type: application/json

{
  "leaveID": "LV1006"
}

### APPROVE LEAVE REQUEST WITH INVALID ID
POST http://localhost:4004/odata/v4/leave-management/approveLeave
Content-Type: application/json

{
  "leaveID": "INVALID_ID"
}

### REJECT LEAVE REQUEST
POST http://localhost:4004/odata/v4/leave-management/rejectLeave
Content-Type: application/json

{
  "leaveID": "LV1007"
}

### REJECT LEAVE REQUEST WITH INVALID ID
POST http://localhost:4004/odata/v4/leave-management/rejectLeave
Content-Type: application/json

{
  "leaveID": "INVALID_ID"
}

### GET INDIVIDUAL EMPLOYEE LEAVES
GET http://localhost:4004/odata/v4/leave-management/getEmployeeLeaves(employeeID='EMP1001')
Content-Type: application/json

### CHANGE LEAVE STATUS
POST http://localhost:4004/odata/v4/leave-management/changeLeaveStatus
Content-Type: application/json

{
  "leaveID": "LV1002",
  "status": "Rejected"
}